# fly.toml app configuration file generated for brandcraft-frontend-nuxt on 2025-02-13T15:48:01+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brandcraft-frontend-nuxt'
primary_region = 'sin'

[build]
  dockerfile = './Dockerfile'

  [build.args]
    NUXT_PUBLIC_BACKEND_URL = 'https://brandcraft-backend.fly.dev'
    NUXT_PUBLIC_FRONTEND_URL = 'https://app.brandcraft.art'
    NUXT_PUBLIC_FRONTEND_DASHBOARD_URL = 'https://app.brandcraft.art/dashboard'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
